name: mercari-list-sync

on:
  schedule:
    # JST(UTC+9)の 09:00 = UTC 00:00
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write Google credentials
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > "${{ github.workspace }}/creds.json"

      - name: Run script (with xvfb)
        env:
          CREDENTIALS_PATH: "${{ github.workspace }}/creds.json"
          # 必要なら下2つを環境変数で差し替え可
          # SPREADSHEET_URL: "https://docs.google.com/..."
          # MERCARI_PROFILE_URL: "https://jp.mercari.com/user/profile/..."
        run: |
          xvfb-run -a python scripts/mii.py

      - name: Upload artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: run-logs
          path: |
            **/*.log
            **/*.csv
